### ISSUE TITLE
bug of pso.py

### ISSUE THREAD

**Issue by FengShan-UTS** [kuhess/pso-ann#5]
In pso.py, the updated velocity is written in Lines 65-69 as follows:
         self.V = self.chi * (
            self.V
            + self.phi_p * R_p * (self.P - self.X)
            + self.phi_g * R_g * (self.g - self.X)
        )
however,  it is written on Wikipedia
vi,d ← w*vi,d + φp*rp*(pi,d-xi,d) + φg*rg*(gd-xi,d)
Does it delete the bracket and change to this code?
self.V = self.chi * self.V + self.phi_p * R_p * (self.P - self.X) + self.phi_g * R_g * (self.g - self.X)

**Comment by kuhess** [comment]
Hi,

The formula on Wikipedia (English) is the inertia formula from:
```
Shi, Yuhui & RC, Eberhart. (1998)
"A Modified Particle Swarm Optimizer"
DOI 10.1109/ICEC.1998.699146 
```

You can use it by using the parameter `omega` instead of `chi` in the `ParticleSwarm#__init__` method.

Note that the formula with `chi` is algebraically equivalent to the formula with `omega`: $\phi_i^{\omega} \iff \chi \times \phi_i^{\chi}$
